/* ================================================================
   posts.js — ASSIST Blog Posts
   Auto-generated by Google Sheets CMS — DO NOT edit manually
   Last sync: 5/15/2026, 1:20:00 PM
   ================================================================ */

var POSTS = [
  {
    id: 'post.CDBGuse',
    date: '2020-04-15',
    category: 'General',
    title: 'CDBG Funding Use',
    subtitle: 'How ASSIST uses CDBG Funds in SLC',
    heroImage: 'https://drive.google.com/thumbnail?id=1SrSCbD3_CA6w0gAlq0nxmSpa-LZw0rWx&sz=w1200',
    body: 'Watch this clip for a quick overview on how ASSIST uses the Community Deveopment Block Grant Funds granted to us every year. \n\nhttps://www.youtube.com/watch?v=vlg-FE5B7ms'
  },
  {
    id: 'post.EntradaRamp',
    date: '2023-05-01',
    category: 'Accessibility',
    title: 'Entrada Ramp Build',
    subtitle: 'Accessibility is needed everywhere',
    heroImage: 'https://drive.google.com/thumbnail?id=1p6UFgr38aNE3W134nchjFTT--YVp7NuZ&sz=w1200',
    body: 'Entrada Institute contacted our Executive Director about the possibility of designing a ramp for their outdoor performance stage. Jason thought it would be even better if our staff took a retreat and went and built it! So we closed up the office for a couple of days, drove to Torrey and built a ramp! We dug (really deep) holes, poured cement and hammered our hearts out while building great relationships.'
  },
  {
    id: 'post.SLCAC',
    date: '2021-05-01',
    category: 'Accessibility',
    title: 'Salt Lake Acting Company Media',
    subtitle: 'Featured ASSIST Architectural design inside',
    heroImage: 'https://drive.google.com/thumbnail?id=1vN7DoTU2I9-TkTvFV_MYl3OHDsPNSq95&sz=w1200',
    body: '5 things you’ll see in the remodel of Salt Lake Acting Company’s quirky former LDS meetinghouse\n\nhttps://gephardtdaily.com/local/salt-lake-acting-company-announces-1m-capital-campaign-to-make-130-year-old-theater-more-accessible/ \n\nhttps://www.saltlakemagazine.com/salt-lake-acting-company-accessibility/ \n\nhttps://dailyutahchronicle.com/2021/05/03/slacs-new-campaign-launch-moves-theatre-towards-accessibility/ \n\nhttps://www.theutahreview.com/spring-theatrical-news-salt-lake-acting-companys-the-amberlee-fund-campaign-sonderimmersives-the-lost-generation-pygmalion-productions-if-this-wall-could-talk/'
  },
  {
    id: 'post.UAF',
    date: '2023-02-27',
    category: 'Community Design',
    title: 'UAF Legacy Health Clinic',
    subtitle: 'UAF Legacy Ribbon Cutting',
    heroImage: 'https://drive.google.com/thumbnail?id=1qqAd_fs1YbvVkzcFD68koU0xrYbTWHeH&sz=w1200',
    body: 'January 25, 2024 was a celebration for Assist, as UAF Legacy Health Clinic held its ribbon cutting. The first-of-its-kind Health center in Utah, focused on LGBTQ+ individuals and allies, was a community design project Assist worked on for two years with UAF. This remodel of their current headquarters expanded to include the health center. Maing this a safe space for both employees and clients was top priority. however, you will find that the center is also beautiful and welcoming instead of your typical stuffy doctors office.'
  },
  {
    id: 'post.NGC',
    date: '2024-06-24',
    category: 'News',
    title: 'Nettie Gregory Center',
    subtitle: 'KUTV Clip Featuring Assist',
    heroImage: 'https://drive.google.com/thumbnail?id=12glG_BFzGPezSbHJmIdZFEQW74PIiUhF&sz=w1200',
    body: 'Assist has worked with board members of Nettie Gregory Center to create an updated design for continued usage of their building. Work was highlighted on KUTV in this clip: https://kutv.com/news/belonging-in-utah/board-members-share-plans-to-revive-slcs-historic-nettie-gregory-center'
  },
  {
    id: 'post.PYHO',
    date: '2025-08-15',
    category: 'Events',
    title: 'Paint Your Heart Out - Service Project',
    subtitle: 'Neighborworks Salt Lake Service Project',
    heroImage: 'https://drive.google.com/thumbnail?id=1hhMzOnRoe-ybyLTsl5knmfr_eFvIBXMo&sz=w1200',
    body: 'Assist joined with NeighborWorks Salt Lake to help paint the home of a local family! It was a beautiful day, slightly overcast with a breeze that made painting on a hot summer day a lot more enjoyable. We appreciate the time away from the office serving our community and building strong neighborhoods'
  },
  {
    id: 'post.groundbreakingDBH',
    date: '2025-12-08',
    category: 'Community Design',
    title: 'Timberwood Creek Housing',
    subtitle: 'Timberwood Creek Housing project with Davis Behavioral Health Breaks Ground',
    heroImage: 'https://drive.google.com/thumbnail?id=1rpzT1H-OHFIwR2KPhSVjVkjhzI_kGHEh&sz=w1200',
    body: 'We\'re excited to shaire construction is underway on Timberwood Ceeek Permanent supportive housing project for Davis Behavioral Health!\n\nOur team is honored to be the architecture and design team for this 60-unit residential housing that is mindfullydesigned to support residents\'s well-being and foster community. The building design thoughtfully incorporates dignified, trauma-informed, and biophillic design principles intended to support mental well-being such as exposed cross-laminated timber (CLT) structure throuhout the building.'
  },
  {
    id: 'post.FPP4',
    date: '2026-04-09',
    category: 'Community Design',
    title: 'Fair Park Phase lll @ The Point Construction Started',
    subtitle: 'Ground Breaking at Fairpark Phase 3 @ The Point',
    heroImage: 'https://drive.google.com/thumbnail?id=11Jmfgevjbrxi2X5iuPo7pFDXci0dfttN&sz=w1200',
    body: 'Developed, owned and managed by Friends of Swichpoint, this 76-unit project will provide affordable housing for indivudals experiencing housing insecurity, continuing the mission of creating stability, dignity, and long term support.'
  },
  {
    id: 'post.SLL',
    date: '2026-05-07',
    category: 'Events',
    title: 'Schluter Lunch & Learn',
    subtitle: 'Schluter Lunch & Learn for Waterproofing and Drains',
    heroImage: 'https://drive.google.com/thumbnail?id=1VJsy1SKB48YK-6y7leb51--btsa2GVRq&sz=w1200',
    body: 'We invited our contractors and staff to a Schluter lunch-and-learn focued on proper waterproofing systems. From installation techniques to long-term maintenance, everyone got hands-on training to help ensure our clients receive durable, high-quality work that lasts.'
  },
  {
    id: 'post.ARK',
    date: '2022-06-07',
    category: 'Community Design',
    title: 'Arkansas Build',
    subtitle: 'Building a House',
    heroImage: 'https://drive.google.com/thumbnail?id=19J4amwhTh_l7IEqQcBzEmmCjetDtDqhg&sz=w1200',
    body: 'Details soon...'
  }
];